import { DateTime } from "luxon";
//https://api.openweathermap.org/data/2.5/weather?q=london&appid=33fe2c7bbf35b409e375473ceb489a70&units=metrics
//https://api.openweathermap.org/data/2.5/onecall?lat=33.44&lon=-94.04&exclude=minutely&appid=33fe2c7bbf35b409e375473ceb489a70&units=metrics

const Base_Url = "https://api.openweathermap.org/data/2.5"
const API_KEY = process.env.REACT_APP_API_KEY
const fetchWeather = async ()=>{
    //const url = new URL()
    
}

        